name: "auto-format"
on:
  pull_request_target:
    types: [opened, synchronize]
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  auto-format:
    # only run on pull requests so long as they don't come from forks
    if: ${{ !( (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name != github.repository) ) }}
    runs-on: ubuntu-latest

    uses: cloudposse/github-action-auto-format/.github/workflows/auto-format-reusable.yml@review-branch
    with:
      # Delete "format-tasks:" values as desired to limit the scope of the overall auto-formatting task.
      format-tasks: "[\"readme\", \"github\", \"terraform\"]"
      bot-name: cloudpossebot
    secrets:
      workflow-token: ${{ secrets.TOKEN_WITH_WORKFLOWS_PERMISSION }}
